[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "mypkg"
version = "0.1.0"
authors = [
    {name="Your Name", email="your.email@example.com"},
]
description = "A sample Python package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/yourusername/mypkg"
Bug Tracker = "https://github.com/yourusername/mypkg/issues"