[project]
name = "mypackage"
version = "0.1.1"
dependencies = [
    "openpyxl",
]
authors = [
  {name = "Yun Wang", email = "595907669@qq.com"},
]
description = "测试用的软件包"

[project.optional-dependencies]
dev = [
    "pytest",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/foo"]