name: week07
channels:
  - conda-forge
dependencies:
  - python=3.12
  - wat-inspector
  - jupyterlab
  - pyarrow
  - perspective-python
  - polars
  - pip
  - pip:
    - tushare
    - perspective-python

